# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhd_poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HHD_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateTimeField(verbose_name='2016.01.09')),
                ('gender', models.TextField(max_length=2)),
            ],
        ),
    ]
